### ISSUE TITLE
I cannot install the library

### ISSUE THREAD

**Issue by leojoker** [jakeyk11/football-data-analytics#2]
I cannot install the library 
analysis_tools.whoscored_custom_events 
analysis_tools.whoscored_data_engineering

**Comment by jakeyk11** [comment]
the library is not installable via PyPi. Please instead import it by cloning the analysis_tools repository and using adding it to the system path. For example:

root_folder = os.path.abspath(os.path.dirname((os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))
sys.path.append(root_folder)

import analysis_tools.get_football_data as gfd
import analysis_tools.whoscored_custom_events
import analysis_tools.whoscored_data_engineering
